import { NextRequest, NextResponse } from 'next/server'

interface SOPTemplate {
  id: string
  name: string
  description: string
  sections: string[]
  template: string
}

const SOP_TEMPLATES: SOPTemplate[] = [
  {
    id: 'sterilization',
    name: 'Sterilization Protocol',
    description: 'Complete substrate sterilization procedure',
    sections: ['Overview', 'Equipment', 'Safety', 'Procedure', 'Quality Control', 'Documentation'],
    template: `# Sterilization Protocol SOP

## Document Information
- **SOP ID**: STE-001
- **Version**: 1.0
- **Date**: {{date}}
- **Author**: Crowe Logic AI
- **Approved By**: Lab Manager

## Overview
This SOP outlines the standard sterilization procedure for substrate preparation in mycology operations.

## Equipment Required
- Pressure cooker/Autoclave (15 PSI minimum)
- Steam gauge
- Timer
- Heat-resistant gloves
- Autoclave bags or containers
- Temperature probe

## Safety Requirements
- Wear heat-resistant gloves when handling hot equipment
- Ensure proper ventilation in sterilization area
- Never open pressure cooker before pressure is fully released
- Check equipment integrity before each use

## Procedure

### Pre-Sterilization
1. Inspect autoclave/pressure cooker for damage
2. Load substrate materials in appropriate containers
3. Add required water to pressure cooker (follow manufacturer specs)
4. Ensure proper sealing of containers

### Sterilization Process
1. Set pressure to 15 PSI (103.4 kPa)
2. Bring to temperature: 121°C (250°F)
3. Sterilize for 90-120 minutes depending on load size
4. Monitor pressure gauge throughout process
5. Record temperature and pressure readings every 15 minutes

### Post-Sterilization
1. Allow natural pressure release (DO NOT force cool)
2. Wait until pressure gauge reads zero
3. Carefully remove sterilized materials
4. Allow cooling in sterile environment
5. Check for container integrity

## Quality Control
- Verify temperature reached 121°C minimum
- Confirm 90+ minute sterilization time
- Visual inspection for proper steam circulation
- Biological indicators recommended weekly

## Documentation
Record the following for each sterilization cycle:
- Date and time
- Load contents and quantity
- Temperature and pressure readings
- Duration of sterilization
- Operator initials
- Any deviations or issues

## Troubleshooting
| Issue | Possible Cause | Solution |
|-------|---------------|----------|
| Low pressure | Insufficient water | Add water, restart cycle |
| Temperature not reached | Faulty gauge | Calibrate equipment |
| Bags torn | Overpacking | Reduce load size |

---
**Document Control**: This is a controlled document. Changes require approval.`
  },
  {
    id: 'inoculation',
    name: 'Inoculation Procedure',
    description: 'Sterile inoculation techniques and protocols',
    sections: ['Overview', 'Preparation', 'Technique', 'Post-Inoculation', 'Quality Control'],
    template: `# Inoculation Procedure SOP

## Document Information
- **SOP ID**: INO-001
- **Version**: 1.0
- **Date**: {{date}}
- **Author**: Crowe Logic AI

## Overview
Standard operating procedure for sterile inoculation of prepared substrates.

## Equipment and Materials
- Laminar flow hood (certified)
- 70% isopropyl alcohol
- Sterile gloves
- Flame source (alcohol burner)
- Inoculation tools (syringes, scalpels)
- Prepared substrate containers
- Culture materials (liquid culture, agar, etc.)

## Preparation
1. Clean and disinfect work surface with 70% alcohol
2. Turn on laminar flow hood 15 minutes before use
3. Arrange all materials within the sterile field
4. Put on sterile gloves
5. Flame sterilize all tools

## Inoculation Technique
1. Work within the sterile field at all times
2. Minimize air currents and movement
3. Flame sterilize tools between each use
4. Use aseptic technique throughout
5. Work quickly but carefully
6. Seal containers immediately after inoculation

## Post-Inoculation
1. Label all inoculated containers with:
   - Date of inoculation
   - Species/strain
   - Operator initials
   - Batch number
2. Move to appropriate incubation environment
3. Begin monitoring schedule

## Quality Control
- Monitor contamination rates
- Document any deviations
- Regular hood certification
- Staff training verification

---
Generated by Crowe Logic AI - {{timestamp}}`
  },
  {
    id: 'harvesting',
    name: 'Harvesting Guidelines',
    description: 'Optimal harvesting timing and techniques',
    sections: ['Overview', 'Timing', 'Technique', 'Post-Harvest', 'Storage'],
    template: `# Harvesting Guidelines SOP

## Document Information
- **SOP ID**: HAR-001
- **Version**: 1.0
- **Date**: {{date}}

## Overview
Guidelines for optimal mushroom harvesting to maximize yield and quality.

## Harvesting Timing
### Visual Indicators
- Cap development stage
- Spore release timing
- Size optimization
- Color changes

### Species-Specific Timing
- **Oyster Mushrooms**: Before caps flatten completely
- **Shiitake**: When caps are 80% open
- **Lion's Mane**: When spines are 0.5-1cm long
- **Reishi**: At desired size/maturity

## Harvesting Technique
1. Use clean, sharp knife or scissors
2. Cut at base of cluster
3. Avoid disturbing substrate
4. Handle gently to prevent bruising
5. Harvest in clean containers

## Post-Harvest Processing
1. Clean mushrooms of debris
2. Trim damaged portions
3. Sort by size and quality
4. Package appropriately
5. Label with harvest date

## Storage Guidelines
- Temperature: 32-36°F (0-2°C)
- Humidity: 90-95%
- Air circulation: Gentle
- Maximum storage: 7-10 days fresh

---
Generated by Crowe Logic AI - {{timestamp}}`
  },
  {
    id: 'contamination',
    name: 'Contamination Response',
    description: 'Contamination identification and response protocols',
    sections: ['Identification', 'Response', 'Disposal', 'Prevention', 'Documentation'],
    template: `# Contamination Response Protocol

## Document Information
- **SOP ID**: CON-001
- **Version**: 1.0
- **Date**: {{date}}

## Contamination Identification

### Visual Signs
- Unusual colors (green, black, pink, yellow)
- Abnormal growth patterns
- Foul odors
- Slimy textures
- Unexpected spore formation

### Common Contaminants
- **Trichoderma** (green mold): Aggressive, fast-growing
- **Aspergillus** (black/yellow): Fuzzy appearance
- **Penicillium** (blue-green): Powdery surface
- **Bacteria**: Slimy, foul-smelling

## Immediate Response
1. **ISOLATE** contaminated material immediately
2. **DO NOT** open containers in main work area
3. Move to designated quarantine area
4. Document findings with photos
5. Alert lab manager

## Disposal Procedure
1. Double-bag contaminated materials
2. Autoclave before disposal if possible
3. Disinfect all surfaces contacted
4. Use appropriate PPE throughout
5. Follow local waste disposal regulations

## Prevention Measures
- Maintain sterile technique
- Regular equipment cleaning
- Environmental monitoring
- Staff training updates
- Quarantine new materials

## Documentation Requirements
- Date and time of discovery
- Location and batch information
- Type of contamination (if known)
- Photos of contamination
- Actions taken
- Possible source analysis

---
Generated by Crowe Logic AI - {{timestamp}}`
  }
]

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const templateId = searchParams.get('template')
    
    if (templateId) {
      const template = SOP_TEMPLATES.find(t => t.id === templateId)
      if (!template) {
        return NextResponse.json({ error: 'Template not found' }, { status: 404 })
      }
      return NextResponse.json({ template })
    }
    
    // Return list of available templates
    const templates = SOP_TEMPLATES.map(({ id, name, description, sections }) => ({ id, name, description, sections }))
    return NextResponse.json({ templates })
  } catch (error) {
    console.error('SOP API error:', error)
    return NextResponse.json({ error: 'Failed to fetch templates' }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const { templateId, customizations = {} } = await request.json()
    
    const template = SOP_TEMPLATES.find(t => t.id === templateId)
    if (!template) {
      return NextResponse.json({ error: 'Template not found' }, { status: 404 })
    }
    
    // Generate SOP with customizations
    let sopContent = template.template
    
    // Replace template variables
    sopContent = sopContent.replace(/\{\{date\}\}/g, new Date().toLocaleDateString())
    sopContent = sopContent.replace(/\{\{timestamp\}\}/g, new Date().toLocaleString())
    
    // Apply customizations
    Object.entries(customizations).forEach(([key, value]) => {
      const placeholder = new RegExp(`\\{\\{${key}\\}\\}`, 'g')
      sopContent = sopContent.replace(placeholder, String(value))
    })
    
    // Generate unique SOP ID
    const sopId = `SOP-${templateId.toUpperCase()}-${Date.now()}`
    
    return NextResponse.json({
      sopId,
      title: template.name,
      content: sopContent,
      templateId,
      generatedAt: new Date().toISOString(),
      customizations
    })
  } catch (error) {
    console.error('SOP generation error:', error)
    return NextResponse.json({ error: 'Failed to generate SOP' }, { status: 500 })
  }
}
